name: Publish Thermite to MyGet

on:
  push:
    paths-ignore:
      - 'docs/**'

env:
  MYGET_FEED: https://www.myget.org/F/thermite/api/v2/package
  CI: true

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-preview.2.20176.6

      - name: Install dependencies
        run: dotnet restore

      - name: Build Thermite
        run: dotnet build --no-restore --configuration Release

#     - name: Run Unit Tests
#       run: dotnet test --no-build --configuration Release

      - name: Pack Thermite
        run: dotnet pack --no-build --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: nupkgs
          path: ${{ github.workspace }}/artifacts/pkg/Release/

      - name: Upload NuGet packages
        run: for pkg in artifacts/pkg/Release/*.nupkg; do dotnet nuget push "$pkg" -k "${{ secrets.MyGet }}" -s "${{ env.MYGET_FEED }}"; done
        shell: bash
